function(read_project_version KEY)
  if(NOT KEY)
    message(FATAL_ERROR "read_project_version: missing KEY")
  endif()

  set(_file "${CMAKE_SOURCE_DIR}/VERSION")
  if(ARGC GREATER 1)
    set(_file "${ARGV1}")
  endif()
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "read_project_version: file not found: ${_file}")
  endif()

  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_file}") # Re-run if VERSION file changes
  file(STRINGS "${_file}" _lines ENCODING UTF-8)

  set(_rhs "")
  foreach(_line IN LISTS _lines)
    string(STRIP "${_line}" _line)
    if(_line STREQUAL "" OR _line MATCHES "^#")
      continue()
    endif()
    if(_line MATCHES "^${KEY}[ \t]*([:=]|[ \t]+)[ \t]*(.+)$")
      set(_rhs "${CMAKE_MATCH_2}")
      break()
    endif()
  endforeach()
  if(_rhs STREQUAL "")
    message(FATAL_ERROR "read_project_version: key '${KEY}' not found in ${_file}")
  endif()

  string(REGEX REPLACE "[ \t]*(#|//).*$" "" _rhs "${_rhs}")
  string(REGEX REPLACE "^[\"'`]" "" _rhs "${_rhs}")
  string(REGEX REPLACE "[\"'`]$" "" _rhs "${_rhs}")
  string(REGEX REPLACE "^[vV][[:space:]]*" "" _rhs "${_rhs}")
  string(STRIP "${_rhs}" _rhs)

  string(REGEX MATCH "[0-9]+(\\.[0-9]+){1,3}" _num "${_rhs}")
  if(_num)
    set(_val "${_num}")
  else()
    set(_val "${_rhs}")
  endif()

  set(${KEY} "${_val}" PARENT_SCOPE)
endfunction()

function(read_project_version_here KEY)
  read_project_version(${KEY} ${ARGN})
  set(${KEY} "${${KEY}}" PARENT_SCOPE)
endfunction()